version: '2'

services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
      # Permite sincronizar la carpeta de trabajo durante el desarrollo
      # de la aplicacion
    networks:
      - dockernetwork
    restart: always
    
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
            #      - mongodata:/data/db
      - ./opt/mongodata:/data/db
    networks:
      - dockernetwork
    restart: always
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=o7n2nQI1gj9h9By

networks:
  dockernetwork:

volumes:
  mongodata:
